### PR TITLE
Make it easier to include as a submodule

### PR DESCRIPTION
**Pull request by KenwoodFox**
Update lib to kicad7
Move footprints into a footprint library

(will duplicate and make variants)

### CODE REVIEW

**Comment by devbisme** [comment]
Hi, did you ever finalize this? (It's still listed as a draft pull request.)

**Comment by KenwoodFox** [comment]
Oh yeah! Sorry about that! I tottally forgot to mark it as ready, we're using it in this project rn https://github.com/FRC-1721/RoomBouy

I don't know if i edited the readme or not, most of my PRs don't get merged! I'll check in a sec

**Comment by KenwoodFox** [comment]
Yep! Readme was updated, if you like the changes, this PR is good to go :+1:

**Comment by devbisme** [comment]
Since you're using this, I'm going to accept the PR without checking. I haven't looked at this repo in years, so you probably understand it better than me.

Thanks for modernizing this!

**Comment by KenwoodFox** [comment]
Yeah ofc! Thanks for originally creating this :) I'll update the credits in my downstream projects :+1:

**Pull request merged**
